name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl: ^0.19.0
  intl_utils: ^2.7.0
  equatable: ^2.0.5
  dio: ^5.4.0
  get_it: ^7.6.4
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: 8.2.1

  template:
    path: ../template
  network:
    path: ../network

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    # - assets/images/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true